name: text-crafter
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  #- _openmp_mutex=4.5
  - absl-py=0.13.0
  - anyio=3.5.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  #- brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - cryptography=36.0.0
  #- cudatoolkit=11.1.74
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - debugpy=1.5.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - fonttools=4.25.0
  #- freetype=2.11.0
  - fsspec=2022.1.0
  - giflib=5.2.1
  #- gmp=6.2.1
  #- gnutls=3.6.15
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  #- intel-openmp=2022.0.1
  - ipykernel=6.4.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.2
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=7.1.2
  - jupyter_core=4.9.1
  - jupyter_server=1.13.5
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  #- ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libcurl=7.80.0
  - libdeflate=1.8
  #- libedit=3.1.20210910
  #- libev
  - libffi=3.3
  #- libgcc-ng
  #- libgfortran-ng=7.5.0
  #- libgfortran4=7.5.0
  #- libgomp=9.3.0
  #- libidn2=2.3.2
  #- libnghttp2=1.46.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  #- libstdcxx-ng=9.3.0
  #- libtasn1=4.16.0
  - libtiff=4.2.0
  #- libunistring=0.9.10
  - libuv=1.40.0
  #- libvpx=1.7.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - munkres=1.1.4
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  #- ncurses=6.3
  - nest-asyncio=1.5.1
  #- nettle=3.7.3
  - networkx=2.6.3
  - notebook=6.4.6
  - numpy-base=1.19.2
  - olefile=0.46
  #- openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1m
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.1.3
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  #- readline=8.1.2
  - requests=2.27.1
  - scikit-image=0.18.1
  - scipy=1.6.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlite=3.37.2
  - terminado=0.13.1
  - testpath=0.5.0
  - tifffile=2021.7.2
  - tk=8.6.11
  - toolz=0.11.2
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  #- x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - antlr4-python3-runtime==4.8
    - bitarray==2.4.1
    - cachetools==5.0.0
    - chunkedfile==0.3.0
    - click==8.0.4
    - colorama==0.4.4
    - coolname==1.1.0
    - decorator==4.4.2
    - dm-env==1.5
    - dm-tree==0.1.6
    - docker-pycreds==0.4.0
    - et-xmlfile==1.1.0
    - fasteners==0.18
    - ffmpeg==1.4
    - filelock==3.6.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - git+https://github.com/openai/CLIP.git
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - gym==0.21.0
    - gym-minigrid==1.0.3
    - huggingface-hub==0.4.0
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - imageio-ffmpeg==0.4.4
    - importlib-resources==5.4.0
    - ipdb==0.13.9
    - ipywidgets==7.7.0
    - joblib==1.1.0
    - jupyterlab-widgets==1.1.0
    - llvmlite==0.38.0
    - markdown==3.3.6
    - matplotlib==3.4.2
    - moviepy==1.0.3
    - natsort==8.1.0
    - nltk==3.7
    - numba==0.55.1
    - numpy==1.21.5
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - openai==0.14.0
    - opencv-python==4.5.3.56
    - openpyxl==3.0.9
    - opensimplex==0.4.2
    - pandas==1.3.0
    - pandas-stubs==1.2.0.48
    - pathtools==0.1.2
    - plotly==5.6.0
    - portalocker==2.4.0
    - proglog==0.1.9
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - regex==2022.3.15
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - sacrebleu==2.0.0
    - sacremoses==0.0.49
    - scikit-learn==1.0.2
    - sentence-transformers==2.2.0
    - sentencepiece==0.1.96
    - sentry-sdk==1.5.6
    - setproctitle==1.2.2
    - shortuuid==1.0.8
    - sklearn==0.0
    - smmap==5.0.0
    - submitit==1.4.1
    - tabulate==0.8.9
    - tb-nightly==2.9.0a20220213
    - tenacity==8.0.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tokenizers==0.11.6
    - toml==0.10.2
    - tqdm==4.62.3
    - transformers==4.17.0
    - wandb==0.12.10
    - werkzeug==2.0.3
    - widgetsnbextension==3.6.0
    - yapf==0.31.0
    - yaspin==2.1.0
